### ISSUE TITLE
"skeet s"を実行するとエラーが発生する

### ISSUE THREAD

**Issue by yuta-kume** [elsoul/skeet#15]
初めまして！👋

[クイックスタート](https://skeet.dev/ja/doc/backend/quickstart/)を行なっていたところ、エラーが発生しました。
` skeet s`を実行すると、以下のエラーが発生します。

```
16640
16638
yarn run v1.22.19
$ run-p skeet:*
$ yarn --cwd functions/openai dev
$ yarn webapp
$ firebase emulators:start
$ yarn build:development:webapp
$ nodemon
$ EXPO_USE_PATH_ALIASES=1 expo start --web
$ expo export:web --dev
[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/**/*
[nodemon] watching extensions: ts,mjs,js,json
[nodemon] starting `npx ts-node devBuild.ts && node ./dist/index.js`
Starting project at /Users/yuta/skeet-sample
Exporting with Webpack...
i  emulators: Shutting down emulators.

Error: Process `java -version` has exited with code 1. Please make sure Java is installed and on your system PATH.
-----Original stdout-----
-----Original stderr-----
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.


Starting Metro Bundler
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "skeet:dev" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

依存パッケージのバージョンは以下です。
- TypeScript 5.1.3
- Node.js v18.16.0
- Yarn v1.22.19
- Google Cloud SDK 435.0.1
- Firebase CLI 12.4.0
- Github CLI 2.31.0

エラー内容を見るとjavaのパスを通さないといけないようですが、クイックスタートにはjavaの記述がありません。
javaの環境構築が必要でしょうか？

**Comment by KishiTheMechanic** [comment]
ありがとうございます！！

もしかしたらjavaが必要だったのかもしれません、インストールしたらどうなるか教えていただけると大変助かります🙏
ちなみにご使用の環境はMacですか？それともLinux系をお使いですか？

**Comment by yuta-kume** [comment]
javaをインストールしてみます！
使用環境はM1 Macです！

**Comment by KishiTheMechanic** [comment]
ありがとうございます！🙌

**Comment by KishiTheMechanic** [comment]
おそらくjavaはメインのスタックではないので要件はそこまで厳しくないはずですが、一応僕の環境は下記になってました！

```
➜  ~ java --version
java 19.0.2 2023-01-17
Java(TM) SE Runtime Environment (build 19.0.2+7-44)
Java HotSpot(TM) 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)
➜  ~ which java
/usr/bin/java
```

**Comment by yuta-kume** [comment]
同じバージョンのjavaをインストールしたらエミュレーターが起動しました！
ただユーザーを登録してログイン後に`http://localhost:19006/rooms`にアクセスしてもログイン画面に飛ばされます。
メールの認証は成功しているようです。
<img width="372" alt="スクリーンショット 2023-06-25 11 34 54" src="https://github.com/elsoul/skeet-cli/assets/73234460/22193226-8a12-48a1-a958-a9a7c2c5f660">

**Comment by KishiTheMechanic** [comment]
やったー！ありがとうございます！

ユーザー登録をした際(もしくはログインを試した際に)cliのサーバーログに出るリンクでverifyを行ってから、`http://localhost:19006`のログイン画面からログインしてもダメそうですか？？

**Comment by KishiTheMechanic** [comment]
すみません、ドキュメントが間違っていたので修正します！

正しいURLは、
`http://localhost:19006/user/open-ai-chat`
になります！🙏

**Comment by KishiTheMechanic** [comment]
すみません、ドキュメントが間違っていたので修正します！
正しくは
`http://localhost:19006/user/open-ai-chat`
になります🙏

**Comment by yuta-kume** [comment]
`test01@test.co.jp`というユーザーを作り、以下の画像のようにログインした後`http://localhost:19006/user/open-ai-chat `にアクセスしましたが、またログイン画面が表示されました。🤔

<img width="400" alt="スクリーンショット 2023-06-25 14 49 32" src="https://github.com/elsoul/skeet-cli/assets/73234460/b9944b31-3049-413c-a0f0-a95c684c586e">

**Comment by KishiTheMechanic** [comment]
ログインすると自動的に`http://localhost:19006/user/open-ai-chat`にリダイレクトされるはずなのですが、
そうはならないですか？？

Succeed to sign inが出ているので、おそらくVerifyは済んでいるはずなのですが、、、
(コンソールに出力されたリンクに飛ばれた後ですよね？)

ブラウザのコンソールログには何かエラーが出ていたりしますか？
基本はWarningだけだと思いますが、何かエラーが出てしまっているかもしれないです、そこをちょっと見てみたいです！

あとは、何か変なキャッシュ等をクリアするために、下記画像のように
Application > Storage > "Clear site data"
をしてブラウザのストレージもクリアしてみてください！

大変お手数おかけしますが何卒よろしくお願いいたします🙏

**Comment by yuta-kume** [comment]
> Succeed to sign inが出ているので、おそらくVerifyは済んでいるはずなのですが、、、
(コンソールに出力されたリンクに飛ばれた後ですよね？)
コンソールに出力された`To verify the email address  〜`のリンクに飛んだ後です。
ブラウザのコンソールログにも特にエラーは出てないようです。
<img width="1920" alt="スクリーンショット 2023-06-26 22 34 09" src="https://github.com/elsoul/skeet-cli/assets/73234460/fb58cb50-6b43-4d4e-8037-eaab703ab4c7">

> Application > Storage > "Clear site data"
をしてブラウザのストレージもクリアしてみてください！

画像を貼っていただいて良いでしょうか？🙇

**Comment by yuta-kume** [comment]
もう一度行ったらエラーが出ました。
<img width="1920" alt="スクリーンショット 2023-06-26 22 41 16" src="https://github.com/elsoul/skeet-cli/assets/73234460/c5a009ec-62be-41af-a1af-a6753bced1d5">

**Comment by KishiTheMechanic** [comment]
すみません、画像貼り忘れました🙏

<img width="1728" alt="Screenshot 2023-06-25 at 22 32 48" src="https://github.com/elsoul/skeet-cli/assets/20677823/c194a3e3-e1fa-4e5e-a2af-1acce0ffd840">


エラーの感じがfirestoreあたりで出てるっぽくて、
http://localhost:4000/のEmulatorモニターで、
AuthとFirestoreでユーザーが作られているか確認していただいてもよろしいですか？？
よろしくお願いいたします！

**Comment by yuta-kume** [comment]
もう一度新しくプロジェクトを作り直したら`http://localhost:19006/user/open-ai-chat`にアクセスできました。🤔
[http://localhost:4000/](http://localhost:4000/%E3%81%AEEmulator%E3%83%A2%E3%83%8B%E3%82%BF%E3%83%BC%E3%81%A7%E3%80%81)でAuthとFirestoreでユーザーが作れられていました。
ありがとうございました！🙇

**Comment by KishiTheMechanic** [comment]
おおおナイスです！！！🙌
良かったです🙌

**Comment by KishiTheMechanic** [comment]
また何かあればなんでもお聞きください🙏
