### ISSUE TITLE
[Question]Why xxxParams not added to index.ts with the skeet add method http?

### ISSUE THREAD

**Issue by euledge** [elsoul/skeet#153]
when create new firebase function, method hello exported to index.ts
but helloParams did not export to index.ts

skeet-cli version 1.11.9
Template of Skeet Next.js (React) - Firestore

``` shell
 skeet add method hello
? Select Instance Type to add http
✔ ./functions/skeet/src/types/http/helloParams.ts created 🎉
✔ ./functions/skeet/src/routings/http/hello.ts created 🎉
✔ Successfully exported to ./functions/skeet/src/index.ts 🎉
```

### functions/skeet/src/types/http/index.ts

Existing parameters are described, but new parameters are not added

``` typescript
export * from './addVertexMessageParams'
export * from './addStreamUserChatRoomMessageParams'
export * from './addUserChatRoomMessageParams'
export * from './createUserChatRoomParams'
export * from './addVertexMessageParams'
import { Request } from 'firebase-functions/v2/https'

export interface TypedRequestBody<T> extends Request {
  body: T
}
```

### functions/skeet/src/routings/http/hello.ts

It seems that index.ts is not used anywhere because the name of the parameter is directly specified in the place where it is imported.

```
import { onRequest } from 'firebase-functions/v2/https'
import { publicHttpOption } from '@/routings/options'
import { TypedRequestBody } from '@/types/http'
import { HelloParams } from '@/types/http/helloParams'

export const hello = onRequest(publicHttpOption, async (req: TypedRequestBody<HelloParams>, res) => {
  try {
    res.json({
      status: 'success'
    })
  } catch (error) {
    res.status(500).json({ status: 'error', message: String(error) })
  }
})
```

**Comment by matheusdsm** [comment]
this could be an error treatment problem.
it's more common that would be.

remembering that error 500 it is not only one HTTP error.

for every HTTP req error, would be nice have every error treatment message.
this helps a lot.

**Comment by POPPIN-FUMI** [comment]
skeet-next v1.3.4 solved this!
