### ISSUE TITLE
Error in skeet init --login

### ISSUE THREAD

**Issue by kazooooo-ma** [elsoul/skeet#227]
## Error message

`Command killed by keyboard interrupt

Service account does not exist, creating new one...
ERROR: (gcloud.iam.service-accounts.create) INVALID_ARGUMENT: The account ID "solv" does not have a length between 6 and 30.
✔ Service account created successfully 🎉`

## Comment
- This will probably use the APPNAME from the skeet create. In this case, I think we should add the number of characters as a validation for skeet create.

**Comment by POPPIN-FUMI** [comment]
Thank you!
It would be awesome if you create PR for it🙏
