### ISSUE TITLE
クイックスタートのページのFirebase Authenticationの有効化の説明の齟齬がある

### ISSUE THREAD

**Issue by euledge** [elsoul/skeet#32]
文書では「Googleログインの有効化」とありますが、画像はEmailログインの画像ではないでしょうか？
ローカルで立ち上げた際の動きではEmailログインのほうが正解だと思いますが、確認をお願いします。

![image](https://github.com/elsoul/skeet-cli/assets/1209580/a5304b2a-d8ca-4f59-92ae-41cdba3c7dc9)

**Comment by KishiTheMechanic** [comment]
ありがとうございます！
修正します👍
