### ISSUE TITLE
The guidance of environment setting OPEN API  KEY is incorrect 

### ISSUE THREAD

**Issue by euledge** [elsoul/skeet#81]
Firestore バックエンドのクイックスタートの中で以下の記載がありますが

```
シークレットキーの設定
skeet add secret コマンドを使って

OpenAI の API キーを環境変数に設定します。

$ skeet add secret CHAT_GPT_ORG
? Enter value for CHAT_GPT_ORG: <yourOpenAIKey>
```
[Enter value for CHAT_GPT_ORG: \<yourOpenAIKey\>](https://github.com/elsoul/skeet-doc/blob/2a6c07a1eee112ea2586fece510629562b44e803/articles/doc/ja/skeet-firestore/quickstart.md?plain=1#L193)
 の部分の案内が誤っていると思います。

正しくは以下の値 `Organization ID` ではないでしょうか?
![image](https://github.com/elsoul/skeet-cli/assets/1209580/6649ac95-731b-4a3f-90ae-0b4eadbd13e5)

**Comment by KishiTheMechanic** [comment]
ご報告ありがとうございます🙌

`CHAT_GPT_ORG`の値はご指摘の通り`Organization ID`になります！
こちらドキュメントの方は修正いたしました！ありがとうございます🙌
