### ISSUE TITLE
Unable to load local environment variables

### ISSUE THREAD

**Issue by euledge** [elsoul/skeet#97]
OPENAI API KEYをローカルの.envファイルに置いたとき、その情報を読み込まない

GraphQL セットアップ文書内の以下のガイダンスに従ってやったが駄目だった
> また、簡易的に試すには、functions/openai/.env に記述することもできますが、 この方法は、本番環境には反映されません。

❌functions/openai/.env → ⭕functions/skeet/.secret.local 
ではないかと思います。

```
i  functions: Loaded environment variables from .env.
⬢  functions: Unable to access secret environment variables from Google Cloud Secret Manager. Make sure the credential used for the Functions Emulator have access or provide override values in /workspaces/skeetdev/app-164/functions/skeet/.secret.local:
        FirebaseError: HTTP Error: 404, Secret [projects/188946830090/secrets/CHAT_GPT_ORG] not found or has no versions.
        FirebaseError: HTTP Error: 404, Secret [projects/188946830090/secrets/CHAT_GPT_KEY] not found or has no versions.
```

**Comment by KishiTheMechanic** [comment]
ありがとうございます！！

こちらですが、以前の挙動では.envも読んでいたはずだったのですが、
もう読まなくなってしまっているでしょうか？
ログにも
`i  functions: Loaded environment variables from .env.`
と出ているので、読んでいると錯覚していました。

.envを読んだ後も、
```
functions: Unable to access secret environment variables from Google Cloud Secret Manager. Make sure the credential used for the Functions Emulator have access or provide override values in /workspaces/skeetdev/app-164/functions/skeet/.secret.local:
        FirebaseError: HTTP Error: 404, Secret [projects/188946830090/secrets/CHAT_GPT_ORG] not found or has no versions.
        FirebaseError: HTTP Error: 404, Secret [projects/188946830090/secrets/CHAT_GPT_KEY] not found or has no versions.
```
こちらのエラーは表示されます。
エラーは表示されるけれど、値は.envから拾っていてChatGPTを実行できる状態でした！

もしかしたら.secret.local推奨に変わったのかもしれません。
ちなみに.secret.localを作成した場合、こちらのエラーが消えて、ChatGPTが使えるようになった感じでしょうか？

いつもご検証いただきありがとうございます！
引き続きよろしくお願いいたします！

**Comment by euledge** [comment]
ご確認いただきありがとうございます。
再度、.envで確認をしたところエラーメッセージは出るものの環境変数の認識はされているようで、Open AIのレスポンスはできました。
こちらの環境でOpenAIのChatができなかったのは #98のエラーのせいだったかもしれません。

.secret.local にした場合はエラーメッセージも出なくなり環境変数としても読み込まれてOpenAIのレスポンス返ってきています。

**Comment by KishiTheMechanic** [comment]
こちらこそご確認いただきありがとうございます！

おおお、では案内としては.secret.localのほうが良さそうですね！
Doc書き換えと各種ignoreに追加して対応しますね🙌

**Comment by KishiTheMechanic** [comment]
v1.6.6以降で作成されたプロジェクトについて、.secret.localが自動的にignoreされるようになっています。
Docにも.secret.localについての記載を追加しました！
ご指摘ありがとうございました🙌
